services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ${REGISTRY:-berserkchmonya}/web:${TAG:-latest}

  team19-web:
    build:
      context: ./team-19-web
      dockerfile: Dockerfile
    image: ${REGISTRY:-berserkchmonya}/team19-web:${TAG:-latest}

  nao-robot-api:
    build:
      context: ./team-19-social-robot/naoRobotAPI
      dockerfile: Dockerfile
    image: ${REGISTRY:-berserkchmonya}/nao-robot-api:${TAG:-latest}

  skeleton-finder-api:
    build:
      context: ./team-19-social-robot/skeletonFinderAPI
      dockerfile: Dockerfile
    image: ${REGISTRY:-berserkchmonya}/skeleton-finder-api:${TAG:-latest}

  translator:
    build:
      context: ./team-19-social-robot/translator
      dockerfile: Dockerfile
    image: ${REGISTRY:-berserkchmonya}/translator:${TAG:-latest}
