apiVersion: apps/v1
kind: Deployment
metadata:
  name: team19-web-deployment
  labels:
    app: team19-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team19-web
  template:
    metadata:
      labels:
        app: team19-web
    spec:
      containers:
        - name: team19-web
          image: berserkchmonya/team19-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: team19-web-service
spec:
  selector:
    app: team19-web
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
